package com.example.miniquiz;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import com.example.miniquiz.QuizContract.*;

import androidx.annotation.Nullable;

import java.util.ArrayList;
import java.util.List;

public class QuizDbHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME = "MiniQuiz.db";
    private static final int DATABASE_VERSION = 1;

    private static QuizDbHelper instance;

    private SQLiteDatabase db;


    private QuizDbHelper( Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    public static synchronized QuizDbHelper getInstance(Context context){
        if (instance == null){
            instance = new QuizDbHelper(context.getApplicationContext());
        }
        return instance;
    }
    @Override
    public void onCreate(SQLiteDatabase db) {
        this.db = db;
        final String SQL_CREATE_SUBJECT_TABLE = "create table "+
                SubjectTable.TABLE_NAME + " ( " +
                SubjectTable._ID + " integer primary key autoincrement, "+
                SubjectTable.COLUMN_NAME + " text "+
                ")";

        final String SQL_CREATE_QUESTIONS_TABLE = "create table "+
                QuestionsTable.TABLE_NAME+" ( "+
                QuestionsTable._ID+" integer primary key autoincrement, "+
                QuestionsTable.COLUMN_QUESTION+ " text, "+
                QuestionsTable.COLUMN_OPTION_1+ " text, "+
                QuestionsTable.COLUMN_OPTION_2+ " text, "+
                QuestionsTable.COLUMN_OPTION_3+ " text, "+
                QuestionsTable.COLUMN_OPTION_4+ " text, "+
                QuestionsTable.COLUMN_ANSWER_NR+ " integer, " +
                QuestionsTable.COLUMN_DIFFICULTY+ " text, "+
                QuestionsTable.COLUMN_SUBJECT_ID+ " integer, "+
                "foreign key(" + QuestionsTable.COLUMN_SUBJECT_ID + ") references "+
                SubjectTable.TABLE_NAME+ "("  + SubjectTable._ID + ")" + "on delete cascade "+
                ")";

        db.execSQL(SQL_CREATE_SUBJECT_TABLE);
        db.execSQL(SQL_CREATE_QUESTIONS_TABLE);
        fillSubjectTable();
        fillQuestionsTable();

    }

    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
        db.execSQL("drop table if exists "+ SubjectTable.TABLE_NAME);
        db.execSQL("drop table if exists "+ QuestionsTable.TABLE_NAME);
        onCreate(db);
    }
    @Override
    public void onConfigure(SQLiteDatabase db){
        super.onConfigure(db);
        db.setForeignKeyConstraintsEnabled(true);
    }

    private void fillSubjectTable(){
        Subject s1 = new Subject("TOC");
        addSubject(s1);
        Subject s2 = new Subject("DBMS");
        addSubject(s2);
        Subject s3 = new Subject("CN");
        addSubject(s3);
        Subject s4 = new Subject("ISEE");
        addSubject(s4);
        Subject s5 = new Subject("SEPM");
        addSubject(s5);
    }
    private void addSubject(Subject subject){
        ContentValues contentValues = new ContentValues();
        contentValues.put(SubjectTable.COLUMN_NAME, subject.getName());
        db.insert(SubjectTable.TABLE_NAME, null, contentValues);
    }

    private void fillQuestionsTable(){
        //--------------------------- TOC --------------------------------//
        Question toc1 = new Question("Let L = {w = (0+1)* | w has even number of 1's}, i.e. L is the set of all bit strings with even number of 1's. Which one of the regular expression below represents L ?",
                "(0*10*1)*","0*(10*10*)*","0*(10*1*)*0*","0*1(10*1)10*",2, Question.DIFFICULTY_Hard, Subject.TOC);
        addQuestion(toc1);
        Question toc2 = new Question("S --> aSa ∣ bSb ∣ a ∣ b The language generated by the above grammar over the alphabet is the set of",
                "All palindromes","All odd length palindromes","Strings that begin and end with the same symbol","All even length palindromes",2, Question.DIFFICULTY_Medium,Subject.TOC);
        addQuestion(toc2);
        Question toc3 = new Question("The number of states required by a Finite State Machine, to simulate the behaviour of a computer with a memory capable of storing 'm' words, each of length 'n' bits is?",
                "M x 2^n","2m+n","2^mn","M+n",3, Question.DIFFICULTY_Hard,Subject.TOC);
        addQuestion(toc3);
        Question toc4 = new Question("An FSM with",
                "1 stack is more powerful than an FSM with no stack","2 stacks is more powerful than a FSM with 1 stack","Both","None",3, Question.DIFFICULTY_Medium,Subject.TOC);
        addQuestion(toc4);
        Question toc5 = new Question("An FSM can be used to add how many given integers",
                "1","4","3","2",4, Question.DIFFICULTY_Easy,Subject.TOC);
        addQuestion(toc5);
        Question toc6 = new Question("For which of the following applications regular expressions can be used ?",
                "Designing compilers","Developing Text editors","Simulating sequential circuits","All",4, Question.DIFFICULTY_Easy,Subject.TOC);
        addQuestion(toc6);
        //--------------------------- DBMS --------------------------------//
        Question dbms1 = new Question("A relational database consists of a collection of",
                "Tables","Fields","Records","Keys",1, Question.DIFFICULTY_Easy, Subject.DBMS);
        addQuestion(dbms1);
        Question dbms2 = new Question("A ________ in a table represents a relationship among a set of values.",
                "Column","Key","Row","Entry",3, Question.DIFFICULTY_Easy,Subject.DBMS);
        addQuestion(dbms2);
        Question dbms3 = new Question("Which term is used to refer a row?",
                "Attribute","Tuple","Field","Instance",2, Question.DIFFICULTY_Easy,Subject.DBMS);
        addQuestion(dbms3);
        Question dbms4 = new Question("Database __________ which is the logical design of the database, and the database _______ which is a snapshot of the data in the database at a given instant in time.",
                "Instance, Schema","Relation, Schema","Relation, Domain","Schema, Instance",4, Question.DIFFICULTY_Medium,Subject.DBMS);
        addQuestion(dbms4);
        Question dbms5 = new Question("Department (dept name, building, budget) and Employee (employee_id, name, dept name, salary)\n" +
                "Here the dept_name attribute appears in both the relations. Here using common attributes in\n" +
                "relation schema is one way of relating ___________ relations.",
                "Attributes of common","Tuple of common","Tuple of distinct","Attributes of distinct",3, Question.DIFFICULTY_Medium,Subject.DBMS);
        addQuestion(dbms5);
        Question dbms6 = new Question("Consider attributes ID, CITY and NAME. Which one of this can be considered as a super key?",
                "NAME","ID","CITY","CITY, ID",2, Question.DIFFICULTY_Medium,Subject.DBMS);
        addQuestion(dbms6);
        Question dbms7 = new Question("Aggregate functions can be used in the select list or the_______clause of a select statement or subquery. They cannot be used in a ______ clause.",
                "Where, having","Having, where","Group by, having","Group by, where",2, Question.DIFFICULTY_Medium,Subject.DBMS);
        addQuestion(dbms7);
        Question dbms8 = new Question("Subqueries cannot:",
                "Use group by or group functions","Retrieve data from a table different from the one in the outer query","Join tables","Appear in select, update, delete, insert statements.",3, Question.DIFFICULTY_Medium,Subject.DBMS);
        addQuestion(dbms8);
        Question dbms9 = new Question("The EXISTS keyword will be true if:",
                "Any row in the subquery meets the condition only","All rows in the subquery fail the condition only","Both of these two conditions are met","Neither of these two conditions is met",1, Question.DIFFICULTY_Medium,Subject.DBMS);
        addQuestion(dbms9);
        Question dbms10 = new Question("Which of the following deletes all tuples in the instructor relation for those instructors associated with a department located in the Watson building which is in department relation.",
                "DELETE FROM instructor WHERE dept_name IN 'Watson';","DELETE FROM department WHERE building='Watson';","DELETE FROM instructor WHERE dept_name IN (SELECT dept name FROM department WHERE building = ’Watson’);","None of the above",3, Question.DIFFICULTY_Hard,Subject.DBMS);
        addQuestion(dbms10);
        Question dbms11 = new Question("Which join refers to join records from the right table that have no matching key in the left table are include in the result set:",
                "Left outer join","Right outer join","Full outer join","Cross join",2, Question.DIFFICULTY_Hard,Subject.DBMS);
        addQuestion(dbms11);
        Question dbms12 = new Question("The operation which is not considered a basic operation of relational algebra is",
                "Join","Selection","Union","Cross product",1, Question.DIFFICULTY_Hard,Subject.DBMS);
        addQuestion(dbms12);
        Question dbms13 = new Question("In SQL the statement 'select * from R, S', is equivalent to",
                "Select * from R natural join S","Select * from R cross join S","Select * from R union join S","Select * from R inner join S",2, Question.DIFFICULTY_Hard,Subject.DBMS);
        addQuestion(dbms13);
        //--------------------------- CN --------------------------------//
        Question cn1 = new Question("PAN stands for ______.",
                "Personal Area Network","Prompt Area Network","Private Area Network","Pear Area Network",1, Question.DIFFICULTY_Easy,Subject.CN);
        addQuestion(cn1);
        Question cn2 = new Question("ISP stands for ______.",
                "International Service Provider","Intermediate Service Provider","Internet Service Provider","Indian Service Provider",3, Question.DIFFICULTY_Easy,Subject.CN);
        addQuestion(cn2);
        Question cn3 = new Question("Who invent www ?",
                "Bob Kahn","Tim Berners Lee","Vint Cerf","None of them",2, Question.DIFFICULTY_Easy,Subject.CN);
        addQuestion(cn3);
        Question cn4 = new Question("“.com” domain definition is ________.",
                "Government","Education","Commercial","International",3, Question.DIFFICULTY_Easy,Subject.CN);
        addQuestion(cn4);
        Question cn5 = new Question("Which device is used to amplify or regenerate digital signals received while sending them from one port of a network into another?",
                "Hub","Bridge","Switch","Repeater",4, Question.DIFFICULTY_Medium,Subject.CN);
        addQuestion(cn5);
        Question cn6 = new Question("Which device modulates analog signal to encode digital information and demodulates carrier signal to decode the transmitted information over the telephone network? ",
                "Hub","Bridge","Switch","Modem",4, Question.DIFFICULTY_Medium,Subject.CN);
        addQuestion(cn6);
        Question cn7 = new Question("What is the speed of standard 10 base T cable?",
                "1 mbps","10 mbps","100 kbps","100 mbps",2, Question.DIFFICULTY_Medium,Subject.CN);
        addQuestion(cn7);
        Question cn8 = new Question(" Which layer in OSI model provides transfer the data between end users?",
                "Network layer","Data link layer","Session layer","Transport layer",4, Question.DIFFICULTY_Medium,Subject.CN);
        addQuestion(cn8);
        Question cn9 = new Question(" What is the purpose of the last three layers in OSI model?",
                "common application services ","data presentation within the end-user system","passing traffic through the network to an end system","manage the dialogue between end user application process",3, Question.DIFFICULTY_Hard,Subject.CN);
        addQuestion(cn9);
        Question cn10 = new Question("A proxy server which communicates with the servers in a local network (for services like decryption, authentication, etc.) is called ______ proxy.",
                "gateway/tunneling","forward proxy","reverse proxy","All of the above",3, Question.DIFFICULTY_Hard,Subject.CN);
        addQuestion(cn10);
        Question cn11 = new Question("The WiFi standard which permits transmission distance of more than 100m with data rate of 100MBPS is ______",
                "IEEE 802.11a","IEEE 802.11b","IEEE 802.11g","IEEE 802.11n",4, Question.DIFFICULTY_Hard,Subject.CN);
        addQuestion(cn11);
        Question cn12 = new Question("TCP/IP port number 69 is assigned for _______.",
                "Telnet","Trivial File Transfer Protocol(TFTP)","Simple Mail Transfer Protocol(SMTP)","File Transfer Protocol(FTP)",2, Question.DIFFICULTY_Hard,Subject.CN);
        addQuestion(cn12);
        //--------------------------- ISEE --------------------------------//
        Question isee1 = new Question("CPI stands for",
                "Consumer price index","Complex price index","Constant price index","Complete price index",1, Question.DIFFICULTY_Easy,Subject.ISEE);
        addQuestion(isee1);
        Question isee2 = new Question("ERP stands for",
                "Education Research Planning","Enterprise Research Planning","Education Resource Planning","Enterprise Resource Planning",4, Question.DIFFICULTY_Easy,Subject.ISEE);
        addQuestion(isee2);
        Question isee3 = new Question("The field that contains data that uniquely identifies a record is called as",
                "the primary key","the public key","the candidate key","the secondary key",1, Question.DIFFICULTY_Easy,Subject.ISEE);
        addQuestion(isee3);
        Question isee4 = new Question("Worm is a",
                "piece of code that attaches itself to legitimate program","malicious program that spreads automatically"," harmful hardware component","hardware component",2, Question.DIFFICULTY_Easy,Subject.ISEE);
        addQuestion(isee4);
        Question isee5 = new Question("The books value of an asset is obtained by deducting depreciation from its",
                "Market value","Scrap value","Market value + cost price","Cost",4, Question.DIFFICULTY_Medium,Subject.ISEE);
        addQuestion(isee5);
        Question isee6 = new Question("A Software that is used to run special purpose processors, which are used in cars, home appliances, medical devices, etc. is reffered as",
                "Application software","System software","Embedded software","Special software",3, Question.DIFFICULTY_Medium,Subject.ISEE);
        addQuestion(isee6);
        Question isee7 = new Question("The practice of charging an interest rate to the principle amount and to any previously accumulated interest that has not been withdrawn is",
                "Simple Interest","Compound Interest","Plain Interest","Complex Interest",2, Question.DIFFICULTY_Medium,Subject.ISEE);
        addQuestion(isee7);
        Question isee8 = new Question("Time value of money is measured in terms of",
                "Principle","Interest rate","Cost","Time",2, Question.DIFFICULTY_Medium,Subject.ISEE);
        addQuestion(isee8);
        Question isee9 = new Question("What is a Commercial bid?",
                "Specification of hardware, software and network made by potential vendor to address the need of an organization","The prices specified for a specific technical bid made by a vendor","Product supplied by vendor","Profit earned by vendor",2, Question.DIFFICULTY_Hard,Subject.ISEE);
        addQuestion(isee9);
        Question isee10 = new Question("Depreciation is",
                "An income","An asset","A loss","A liability",3, Question.DIFFICULTY_Hard,Subject.ISEE);
        addQuestion(isee10);
        Question isee11 = new Question(" Cash paid for preferred stock dividends should be shown on the statement of cash flows under?",
                "Investing activities","Financing activities","Non cas investing","Operating activities",2, Question.DIFFICULTY_Hard,Subject.ISEE);
        addQuestion(isee11);
        Question isee12 = new Question("Centralized IT system is best suited for",
                "small sized organization","large sized organization","Complex flow organization","Huge Organization",1, Question.DIFFICULTY_Hard,Subject.ISEE);
        addQuestion(isee12);
        Question isee13 = new Question("________ costs are incurred by the purchasing assets to be used in production and service",
                "Operating","Capital recovery","Fix","Variable",2, Question.DIFFICULTY_Hard,Subject.ISEE);
        addQuestion(isee13);
        //--------------------------- SEPM --------------------------------//
        Question sepm1 = new Question("Which of the following is not a Software Development Life Cycle Phase?",
                "Requirements Gathering","Test Closure","Coding","Testing",2, Question.DIFFICULTY_Easy,Subject.SEPM);
        addQuestion(sepm1);
        Question sepm2 = new Question("The UML was designed for describing _________",
                "object-oriented systems","architectural design","SRS","Both 1 and 2",4, Question.DIFFICULTY_Easy,Subject.SEPM);
        addQuestion(sepm2);
        Question sepm3 = new Question("What is TestNG ?",
                "TestNextGeneration","TestNewGeneralization","TestNewGeneration","TestNaiveGenerations",1, Question.DIFFICULTY_Easy,Subject.SEPM);
        addQuestion(sepm3);
        Question sepm4 = new Question("RMMM stands for",
                "risk mitigation methodology and management","risk mitigation manupulation and management","risk mitigation monitoring and management","risk mitigation measurement and management",3, Question.DIFFICULTY_Easy,Subject.SEPM);
        addQuestion(sepm4);
        Question sepm5 = new Question("Which of the following is not part of the software reengineering process model?",
                "reverse engineering","forward engineering","inventory analysis","prototyping",4, Question.DIFFICULTY_Easy,Subject.SEPM);
        addQuestion(sepm5);
        Question sepm6 = new Question("Consider the following partial description of the IIT security software.\n" +
                "“A camera at themain gate should detect an incoming vehicle, and the gate\n" +
                "should be opened for registeredvehicles.” Which one of the following types of\n" +
                "requirements is this?",
                "Functional requirement","Non-Functional requirement","Design requirement","Design constraint",1, Question.DIFFICULTY_Medium,Subject.SEPM);
        addQuestion(sepm6);
        Question sepm7 = new Question("Which of the following is not real-time architectural patterns that are commonly used?",
                "Asynchronous communication","observe and react","Environmental Control","Process Pipeline",1, Question.DIFFICULTY_Medium,Subject.SEPM);
        addQuestion(sepm7);
        Question sepm8 = new Question("Which of the following is not a software testing generic characteristics?",
                "Different testing techniques are appropriate at different points in time","Testing is conducted by the developer of the software or an independent test group","Testing and debugging are different activities, but debugging must be accommodated in any testing strategy","None",1, Question.DIFFICULTY_Medium,Subject.SEPM);
        addQuestion(sepm8);
        Question sepm9 = new Question("What is “V” Model?",
                "Test Design Technique","Test type","SDLC model","Test level",3, Question.DIFFICULTY_Medium,Subject.SEPM);
        addQuestion(sepm9);
        Question sepm10 = new Question("________is not a Software Test Life Cycle Phase?",
                "Requirements Gathering","Test planning","Test Closure","Test Design",1, Question.DIFFICULTY_Hard,Subject.SEPM);
        addQuestion(sepm10);
        Question sepm11 = new Question("Which architectural style goal is to achieve Modifiability with Scalability?",
                "Data Flow Architecture","Call and Return Architecture","Data Centered Architectures","Both a and b",2, Question.DIFFICULTY_Hard,Subject.SEPM);
        addQuestion(sepm11);
        Question sepm12 = new Question("The modification of the software to match changes in the ever\n" +
                "changing environment,falls under which category of software maintenance?",
                "Adaptive","Corrective","Prefecture","Preventive",1, Question.DIFFICULTY_Hard,Subject.SEPM);
        addQuestion(sepm12);
        Question sepm13 = new Question("The __________ enables the software engineer to develop models of the information domain and functional domain at the same time",
                "Data flow diagram","State transition diagram","Control specification","Activity diagram",3, Question.DIFFICULTY_Hard,Subject.SEPM);
        addQuestion(sepm13);

    }
    private void addQuestion(Question question){
        ContentValues cv = new ContentValues();
        cv.put(QuestionsTable.COLUMN_QUESTION, question.getQuestion());
        cv.put(QuestionsTable.COLUMN_OPTION_1, question.getOption1());
        cv.put(QuestionsTable.COLUMN_OPTION_2, question.getOption2());
        cv.put(QuestionsTable.COLUMN_OPTION_3, question.getOption3());
        cv.put(QuestionsTable.COLUMN_OPTION_4, question.getOption4());
        cv.put(QuestionsTable.COLUMN_ANSWER_NR, question.getAnswerNr());
        cv.put(QuestionsTable.COLUMN_DIFFICULTY, question.getDifficulty());
        cv.put(QuestionsTable.COLUMN_SUBJECT_ID, question.getSubjectID());
        db.insert(QuestionsTable.TABLE_NAME, null, cv);
    }
    public List<Subject> getAllSubjects(){
        List<Subject> subjectList = new ArrayList<>();
        db = getReadableDatabase();
        Cursor c = db.rawQuery("select * from "+ SubjectTable.TABLE_NAME, null);
        if(c.moveToFirst()){
            do{
                Subject subject = new Subject();
                subject.setId(c.getInt(c.getColumnIndex(SubjectTable._ID)));
                subject.setName(c.getString(c.getColumnIndex(SubjectTable.COLUMN_NAME)));
                subjectList.add(subject);
            }while(c.moveToNext());
        }
        c.close();
        return subjectList;
    }

    public List<Question> getAllQuestions(){
        List<Question> questionList = new ArrayList<>();
        db = getReadableDatabase();
        Cursor c = db.rawQuery("select * from "+QuestionsTable.TABLE_NAME, null);
        if(c.moveToFirst()){
            do{
                Question question = new Question();
                question.setId(c.getInt(c.getColumnIndex(QuestionsTable._ID)));
                question.setQuestion(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_QUESTION)));
                question.setOption1(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_1)));
                question.setOption2(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_2)));
                question.setOption3(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_3)));
                question.setOption4(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_4)));
                question.setAnswerNr(c.getInt(c.getColumnIndex(QuestionsTable.COLUMN_ANSWER_NR)));
                question.setDifficulty(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_DIFFICULTY)));
                question.setSubjectID(c.getInt(c.getColumnIndex(QuestionsTable.COLUMN_SUBJECT_ID)));
                questionList.add(question);
            }while (c.moveToNext());
        }
        c.close();
        return questionList;
    }
    public List<Question> getQuestions(int subjectID, String difficulty){
        List<Question> questionList = new ArrayList<>();
        db = getReadableDatabase();
        String selection = QuestionsTable.COLUMN_SUBJECT_ID + " = ? "+
                " and " + QuestionsTable.COLUMN_DIFFICULTY + " = ? ";
        String[] selectionArgs = new String[]{String.valueOf(subjectID), difficulty};
        Cursor c = db.query(
                QuestionsTable.TABLE_NAME,
                null,
                selection,
                selectionArgs,
                null,
                null,
                null
        );
        if(c.moveToFirst()){
            do{
                Question question = new Question();
                question.setId(c.getInt(c.getColumnIndex(QuestionsTable._ID)));
                question.setQuestion(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_QUESTION)));
                question.setOption1(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_1)));
                question.setOption2(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_2)));
                question.setOption3(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_3)));
                question.setOption4(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_OPTION_4)));
                question.setAnswerNr(c.getInt(c.getColumnIndex(QuestionsTable.COLUMN_ANSWER_NR)));
                question.setDifficulty(c.getString(c.getColumnIndex(QuestionsTable.COLUMN_DIFFICULTY)));
                question.setSubjectID(c.getInt(c.getColumnIndex(QuestionsTable.COLUMN_SUBJECT_ID)));
                questionList.add(question);
            }while (c.moveToNext());
        }
        c.close();
        return questionList;
    }

}
